### PR TITLE
Demos in Google Colaboratory

### PR DESCRIPTION
**Pull request by Rauf-Kurbanov**
https://github.com/Synthesis-AI-Dev/face_api_dataset/issues/17

### CODE REVIEW

**Review by adavydow — COMMENTED** [review]
Please add library installing code to colab notebook.

**Comment by adavydow** [comment]
> Please add library installing code to colab notebook.

Irrellevant, loaded old verison by accident.

**Comment by adavydow** [comment]
Minor:
image
Length of dataset in text description differs from real one.

**Comment by Rauf-Kurbanov** [comment]
fixed

> Minor:
> image
> The length of the dataset in text description differs from the real one.

fixed

**Pull request merged**
