### PR TITLE
3dprojection

### PR DESCRIPTION
**Pull request by GulevskiyDaniil**

### CODE REVIEW

**Comment by vsevolod-oparin** [comment]
Hey, in general looks good. I would put in the very beginning what do you show as some form of abstract. Right before all the installation.

On notebook:

1. I would delete the output from the installation part. They add clutter but not value.
2. Do you think it is even possible to hide it in the separate script?
3. 
```
dataset = FaceApiDataset(data_root,
                        modalities=[Modality.RGB, Modality.CAM_INTRINSICS, Modality.LANDMARKS_3D_IBUG68,
                                    Modality.LANDMARKS_IBUG68, Modality.DEPTH,
                                    Modality.LANDMARKS_DENSE_MEDIAPIPE, Modality.LANDMARKS_DENSE_SAI
                                   ])
```
nit: Can we have all modalities each on a new line? It just makes it easier to read them.
4. item2 is never used.
5. scene_camera seems to be used the same at all places. May we extract a variable and format it in a nice way? Like what json.dumps with indent does.
6. 3D space. Does it repeat help function as before? No images to be shown?
7. Dataset overview rotated the images 90 degrees. Is this expected?

**Comment by vsevolod-oparin** [comment]
image

**Comment by GulevskiyDaniil** [comment]
1. +
2. you mean to hide installation outputs from other jupyter notebooks?
3. +
4. +
5. not sure, maybe later
6. Yes, to make it able to run just from this place (to run all previous cells is not mandatory)
7. Yes! As it is in dataset
5. not sure, maybe later
6. Yes, to make it able to run just from this place (to run all previous cells is not mandatory)
7. Yes! As it is in dataset

**Comment by vsevolod-oparin** [comment]
2. I assumed to extract it into a separate script. As soon as all notebooks install the same.
5. Ok
6. Ok
7. Ok

**Comment by GulevskiyDaniil** [comment]
2. I think, It will be not convenient. Because, as I understand, usually customers open our notebooks in google colab. And It rather simpler to have few cells with installation process.

**Comment by vsevolod-oparin** [comment]
Also, I see lots of cells as below. It seems they have to show something, but haven't been executed. Was it assumed?

image

**Comment by GulevskiyDaniil** [comment]
These outputs are too large because they are 3D plots. So, It was a reason why last time this jupyter did not open in github.

**Comment by vsevolod-oparin** [comment]
I see. Just thinking if we want to add some comments that we haven't rendered the outputs on purpose. Or include some screenshots about what to expect.

Generally, it is fine to me. I would probably nudge @adavydow just to see if it meets the standards of public repositories.

**Pull request merged**
